services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: businesses
      MONGO_INITDB_ROOT_PASSWORD: hunter2
      MONGO_INITDB_DATABASE: businesses
    restart: on-failure
    networks:
      - mongo-net

  db-init:
    build: .
    environment:
      MONGO_HOST: db
      MONGO_USER: businesses
      MONGO_PASSWORD: hunter2
      MONGO_DB_NAME: businesses
      MONGO_AUTH_DB_NAME: hunter2
      MONGO_CREATE_USER: businesses
      MONGO_CREATE_PASSWORD: hunter2
    depends_on:
      - db
    restart: on-failure
    command: npm run initdb
    networks:
      - mongo-net

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: db
      MONGO_USER: businesses
      MONGO_PASSWORD: hunter2
      MONGO_DB_NAME: businesses
      MONGO_AUTH_DB_NAME: businesses
    depends_on:
      - db
      - db-init
    restart: on-failure
    command: npm start
    networks:
      - mongo-net

networks:
  mongo-net: